### ISSUE TITLE
Job System Support?

### ISSUE THREAD

**Issue by SolAZDev** [Extrys/Hybrid-EZS#1]
Are there plans to integrate, or lay a groundwork for the Job System, which is now [out of preview](https://docs.unity3d.com/Manual/JobSystem.html)? 
It seems it would give an extra performance boost as it'll manage threads with relative ease. The only issue I've had in a non ECS workflow, is that they work with objects that cannot have any nullables variables.

**Comment by Extrys** [comment]
Well technically the workflow is designed not to replace ECS but help with the transition from monobehaviours, as you still transiting then you wont need the Entity injector, once every component is ported to ECS component

Anyways you can stilll working with JOBS if you add ECS Components through the entity injector with the custom Authoring components
since you "inject" a entity with Non nullable components, so if the systems iterates with these components you can jobify it and even Burst compile it

TDLR: You can still use Entityes.Foreach Using burst and jobs as long as you iterate trough non nullable data

In the documentation (which is not complete yet) says this:

> Autoring Data:
> This lists is mainly to attach custom IComponentData to entities from the AutoringComponent who are added to the list (We will talk about this in an easier way in the next section)
